# Generated by Django 5.0 on 2024-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='credit',
            field=models.CharField(default='6', max_length=150),
        ),
    ]
