# Generated by Django 5.0 on 2024-02-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_headofdepartment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='class',
            name='graduated',
        ),
    ]
